name: Static tests

on:
  push:
    branches:
      - main
      - gh-pages
  pull_request:

jobs:
  powershell-static-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run static regression tests
        shell: pwsh
        run: ./tests/run-tests.ps1
